const js = require("@eslint/js");

module.exports = [
  js.configs.recommended,
  {
    files: ["main.js", "preload.js", "js/**/*.js", "src/**/*.js"],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: "commonjs",
      globals: {
        // Browser
        document: "readonly",
        window: "readonly",
        localStorage: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        console: "readonly",
        location: "readonly",
        navigator: "readonly",
        URL: "readonly",
        Blob: "readonly",
        fetch: "readonly",
        getComputedStyle: "readonly",
        requestAnimationFrame: "readonly",
        prompt: "readonly",
        // Global config (config.js)
        TASK_TEMPLATES: "readonly",
        FREQ_LABELS: "readonly",
        CHANNEL_CARDS: "readonly",
        questionnaires: "readonly",
        // Node.js
        __dirname: "readonly",
        process: "readonly",
        require: "readonly",
        module: "readonly",
        Buffer: "readonly",
        // Electron
        CustomEvent: "readonly",
        // Global functions from app.js
        switchPage: "readonly",
        sendMessage: "readonly",
        handleRole: "readonly",
        cancelStream: "readonly",
        showDialog: "readonly",
        closeDialog: "readonly",
        showRecharge: "readonly",
        closeRecharge: "readonly",
        toggleModelSwitcher: "readonly",
        newConversation: "readonly",
        exportChat: "readonly",
        initAuth: "readonly",
        openErp: "readonly",
        refreshCredits: "readonly",
        refreshTasks: "readonly",
        refreshChannels: "readonly",
        refreshReports: "readonly",
        refreshSettings: "readonly",
        showAddTask: "readonly",
        hideAddTask: "readonly",
        updateCreditsBadge: "readonly",
        startFeishuPolling: "readonly",
        loadSkills: "readonly",
        loadMemories: "readonly",
        loadModelConfig: "readonly",
        loadBillingData: "readonly",
        showActivationOverlay: "readonly",
        saveAuth: "readonly",
        skipBootstrap: "readonly",
        skipOnboarding: "readonly",
        nextOnboardingStep: "readonly",
        renderSidebar: "readonly",
        restoreLastState: "readonly",
        initOnboarding: "readonly",
        pushToFeishu: "readonly",
        handleFileSelect: "readonly",
        quickReminder: "readonly",
        showPipelineConfig: "readonly",
        closePipelineConfig: "readonly",
        togglePipelineMode: "readonly",
        restartGatewayFromUI: "readonly",
        dismissPageTip: "readonly",
        dismissLowCreditsBanner: "readonly",
        updateCostEstimate: "readonly",
        hideConnBanner: "readonly",
        showConnBanner: "readonly",
        filePreview: "readonly",
        closeFilePreview: "readonly",
        showBillingHistory: "readonly",
        closeBillingHistory: "readonly",
        switchBillingTab: "readonly",
        closeMemoryEditor: "readonly",
        // Hermes global
        hermes: "readonly",
        hermes_on: "readonly",
        ROLES: "writable",
        QRCode: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" }],
      // Phase 0: no-empty is warn. Will be promoted to error in Phase 4 after all catch blocks are audited.
      "no-empty": ["warn", { allowEmptyCatch: false }],
      "no-console": "off",
      "no-constant-condition": ["error", { checkLoops: false }],
      "no-undef": "warn", // Phase 1 模块化后升为 error
      "no-extra-semi": "warn",
      "no-unreachable": "warn",
      "no-extra-boolean-cast": "warn", // !! 是常见 JS 惯用法
      "no-useless-escape": "warn", // Phase 1 清理
      "no-regex-spaces": "warn", // Phase 1 清理
      "no-control-regex": "warn", // 匹配 ANSI/终端字符，合法
      "no-useless-assignment": "warn", // Phase 1 清理死代码
    },
  },
  {
    // Jest test files
    files: ["tests/**/*.js", "tests/**/*.ts"],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: "commonjs",
      globals: {
        describe: "readonly",
        test: "readonly",
        it: "readonly",
        expect: "readonly",
        jest: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
        require: "readonly",
        module: "readonly",
        __dirname: "readonly",
        process: "readonly",
        console: "readonly",
        Buffer: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        global: "writable",
      },
    },
  },
  {
    ignores: [
      "node_modules/**",
      "release/**",
      "dist/**",
      "js/vendor/**",
      "backups/**",
      "*.min.js",
    ],
  },
];
